---
machine:
  network:
    hostname: k0
    interfaces:
      - interface: end0
        dhcp: true
        vip:
          ip: 10.0.2.1
  install:
    disk: /dev/mmcblk0
    image: factory.talos.dev/metal-installer/84c9c1764180a97c7499a3715d76400622d2b24455387b659ae4016b158eac9b:v1.13.3
  features:
    kubernetesTalosAPIAccess:
      allowedKubernetesNamespaces:
        - system-upgrade # or the namespace the controller will be installed to
      allowedRoles:
        - os:admin
      enabled: true
cluster:
  controlPlane:
    endpoint: https://10.0.2.1:6443
  apiServer:
    extraArgs:
      oidc-issuer-url: https://dex.homelab.evilcyborgdrone.com
      oidc-client-id: kube-apiserver
      oidc-username-claim: email
      oidc-groups-claim: groups
    certSANs:
      - 10.0.1.1
      - k.lan
      - k0.lan
  allowSchedulingOnControlPlanes: true
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381

---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == 'usb'
  minSize: 30GB
  maxSize: 30GB
  grow: false

---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: csi-data
provisioning:
  diskSelector:
    match: "!system_disk"
  minSize: 2GB
