---
machine:
  network:
    hostname: k3
    interfaces:
      - interface: eno1
        dhcp: true

  install:
    disk: /dev/nvme1n1
    image: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.13.3
